#!/bin/bash
# Quick Start Guide for MPI Large Number Addition

echo "========================================"
echo "  QUICK START GUIDE"
echo "========================================"
echo ""
echo "BUILD:"
echo "  make"
echo ""
echo "RUN WITH MENU (interactive):"
echo "  mpirun -np 5 ./Tema_3 100 100"
echo ""
echo "RUN SPECIFIC VARIANT (command line):"
echo "  mpirun -np 5 ./Tema_3 <N1> <N2> <variant>"
echo ""
echo "VARIANTS:"
echo "  0 - Sequential (reference)"
echo "  1 - Variant 1: Standard Communication"
echo "  2 - Variant 2: Scatter/Gather"
echo "  3 - Variant 3: Asynchronous"
echo "  4 - Variant 1.1: Optimized"
echo "  5 - Run ALL + verification"
echo "  6 - Verification only"
echo ""
echo "OUTPUT FILES:"
echo "  result.txt          - Sequential (reference)"
echo "  result1.txt         - Variant 1"
echo "  resultScatter.txt   - Variant 2"
echo "  resultAsync.txt     - Variant 3"
echo "  resultOptimized.txt - Variant 1.1"
echo ""
echo "EXAMPLES:"
echo "  # Run Variant 1 with 100 digits, 5 processes"
echo "  mpirun --oversubscribe -np 5 ./Tema_3 100 100 1"
echo ""
echo "  # Run all variants with verification"
echo "  mpirun --oversubscribe -np 5 ./Tema_3 1000 1000 5"
echo ""
echo "  # Run Scatter/Gather with 4 processes"
echo "  mpirun --oversubscribe -np 4 ./Tema_3 16 16 2"
echo ""
echo "  # Verify existing results"
echo "  mpirun -np 2 ./Tema_3 100 100 6"
echo ""
echo "========================================"

